import Footer from "./footer";
import Header from "./header";
import Head from "next/head"
import CssBaseline from '@mui/material/CssBaseline';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import { Grid } from "@mui/material";

const theme = createTheme();

function Layout({children}){
    return(
    <>
        <Head>
                <title>Desafio React Framework</title>
                <meta name="description" content="Generated by created next app" />
                <link rel="icon" href="/logo.ico"/> 
                     
        </Head>
        <Header />
        <ThemeProvider theme={theme}>
            <CssBaseline />
                <main>
                <Grid sx={{ padding: "3rem", backgroundColor: "#F9F7F0"}}>
                    {children}
                </Grid>
                </main>
        </ThemeProvider>
        <Footer />
    </>
    )
}

export default Layout;